name       : gummi
version    : 0.8.2
release    : 3
source     :
    - https://github.com/alexandervdm/gummi/releases/download/0.8.2/gummi-0.8.2.tar.gz : 5ad486da1f98407a806519f3a8b2b149b145af6f9cf0a438519dd1df8c066728
license    : MIT
component  : editor
summary    : Simple LaTeX editor
description: |
    The simple LaTeX editor.
builddeps  :
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(poppler-glib)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(synctex)
setup      : |
    %patch -p1 < $pkgfiles/fix_synctex_version.patch
    %configure
build      : |
    %make
install    : |
    %make_install
