name       : gummi
version    : 0.8.3
release    : 4
source     :
    - https://github.com/alexandervdm/gummi/releases/download/0.8.3/gummi-0.8.3.tar.gz : c1769fea45c23bf892bdbf524c92ddf83eae21b1ddba358d4173155aadea898e
homepage   : https://gummi.app/
license    : MIT
component  : editor
summary    : Simple LaTeX editor
description: |
    The simple LaTeX editor.
builddeps  :
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(poppler-glib)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(synctex)
rundeps    :
    - texlive
setup      : |
    %patch -p1 < $pkgfiles/fix_synctex_version.patch
    %configure
build      : |
    %make
install    : |
    %make_install
